# Introduction to Numpy

### Numpy is a python library that is use for numerical computation
### Example:
### - Linear algebra
### - Matrices
### Fourier Transform

### Key Features
#### - 
#### - 
#### - 

### How to Install Numpy?


### Creating Arrays

In [68]:
import numpy as np

In [69]:
# 1D  array
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [70]:
# 2D array
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
# 3D array
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Operations
- Broadcasting

In [72]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# Broadcasting
arr2*6 # padding 6

array([[ 6, 12, 18],
       [24, 30, 36]])

In [74]:
# Broadcasting
arr1 + 5

array([6, 7, 8])

In [75]:
# numpy operations
# .sum
print(arr1, np.sum(arr1)) # add all element in array
print(arr2, np.sum(arr2))

[1 2 3] 6
[[1 2 3]
 [4 5 6]] 21


### How to access numpy arrays

In [76]:
arr1[0]

1

In [77]:
arr2[0]

array([1, 2, 3])

In [78]:
arr2[0][1]

2

### Other Numpy Functions


In [79]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
np.zeros((1,1))

array([[0.]])

In [82]:
np.ones((1,1))

array([[1.]])

In [83]:
np.linspace(0,20,5) # start, end, number of values

array([ 0.,  5., 10., 15., 20.])

In [84]:
np.linspace(0,10,5) # start, end, number of values

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [85]:
np.linspace(1,16,2)

array([ 1., 16.])

In [86]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [87]:
# cannot accept negative values
# np.linspace(-1,-16, -2)

In [88]:
# generating random numbers
np.random.rand(3,3)

array([[0.4516387 , 0.70123788, 0.69703612],
       [0.84572228, 0.64764264, 0.1886882 ],
       [0.94941303, 0.39784584, 0.77446054]])

In [89]:
np.random.rand(0,10)

array([], shape=(0, 10), dtype=float64)

In [90]:
# Applying trigonometric Functions
# np.pi, np.sin(), np.cosine()
np.pi

3.141592653589793

In [91]:
angles = np.array([0, np.pi/2, np.pi])
angles

array([0.        , 1.57079633, 3.14159265])

In [92]:
sine_values = np.sin(angles) # compute the sine of each element
sine_values

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])